# version: '3.8'
# services:
#   frontend:
#     build: ./
#     ports:
#       - "8080:8080"
  
#   backend:
#     build: ./backend
#     ports:
#       - "3000:3000"

version: '3.8'
services:
  frontend:
    build: ./
    ports:
      - "8080:8080"
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:dev@db:5432/splitifydb
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: splitifydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
